name = "fiber"
version = "1.0.0"
gleam = ">= 1.5.0"
description = "An implementation of the JSON-RPC 2.0 protocol in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "drowrin", repo = "fiber" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_otp = ">= 0.12.0 and < 1.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"
youid = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.3 and < 2.0.0"
